create table request
(
    id              int8 generated by default as identity,
    license_id      int8           not null,
    user_id         int8           not null,
    status          varchar(50)    not null,
    requested_on    date           not null,
    start_of_use    date           not null,
    primary key (id)
);