create table "user"
(
    id              int8 generated by default as identity,
    f_name          varchar(50)    not null,
    l_name          varchar(50)    not null,
    workplace_id    int8           not null,
    active          boolean        not null,
    last_active     date           not null,
    primary key (id)
);