create table credential
(
    id              int8 generated by default as identity,
    username        varchar(50)    not null,
    password        varchar(50)    not null,
    license_id      int8           not null,
    primary key (id)
);