create table license
(
    id              int8 generated by default as identity,
    name            varchar(50)    not null,
    website         varchar(50)    not null,
    license_type    varchar(50)    not null,
    description     text,
    logo            bytea          not null,
    cost            numeric(6, 2)  not null,
    currency_id     int8           not null,
    duration        integer        not null,
    duration_unit   varchar(50)    not null,
    expires_on      date           not null,
    recurring       boolean        not null,
    seats           integer        not null,
    primary key (id)
);