
ALTER TABLE "user" DROP CONSTRAINT user_workplace_id_fk;

DROP TABLE IF EXISTS workplace;

CREATE TABLE workplace(
id                            int8 generated by default as identity,
position_id                   int8 NOT NULL REFERENCES position(id) ON DELETE CASCADE,
delivery_unit_id              int8 NOT NULL REFERENCES delivery_unit(id) ON DELETE CASCADE,
discipline_id                 int8 NOT NULL REFERENCES discipline(id) ON DELETE CASCADE,
PRIMARY KEY(id)
);

alter table if exists "user"
    add constraint user_workplace_id_fk foreign key (workplace_id) references workplace(id) on delete cascade;

alter table if exists user_role
    drop constraint user_role_user_id_fk;

alter table if exists user_role
    add constraint user_role_user_id_fk_cascade foreign key (user_id) references "user" ON DELETE CASCADE;
alter table "user" alter column last_active drop not null;