create table workplace
(
    id                int8 generated by default as identity,
    du_name           varchar(50)    not null,
    location_id       int8           not null,
    discipline_id     int8           not null,
    primary key (id)
);